apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: metrics-probe
  name: metrics-probe
  namespace: kube-system
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: metrics-probe
      name: metrics-probe
    spec:
      # We "borrow" heapster's account ;)
      serviceAccountName: heapster
      containers:
        - name: metrics-probe
          image: eiger-1.maas:5000/metrics-probe:1.5
          # Uncomment for debugging. Attach using kubectl attach -ti -n kube-system <pod-name>
#          command:
#          - python
#          - -u
#          stdin: true
#          tty: true
          resources:
            limits:
              intel.com/sgx: 1
            requests:
              intel.com/sgx: 1
          volumeMounts:
          - mountPath: /var/run/docker.sock
            name: dockersock
          - mountPath: /hostproc
            name: hostproc
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: hostproc
        hostPath:
          path: /proc
          type: Directory
