version: "3"
services:
  cadvisor:
    image: google/cadvisor:v0.26.1
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command: ["-storage_driver=influxdb", "-storage_driver_host=influx:8086"]
    links:
      - influx
    deploy:
      mode: global
    ports:
      - "8080:8080"
  influx:
    image: influxdb:1.2.4
    volumes:
      - /mnt/data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
    expose:
      - "8090"
      - "8099"
    environment:
      - PRE_CREATE_DB=cadvisor
  grafana:
    image: grafana/grafana:4.3.2
    ports:
      - "3000:3000"

